# Generated by Django 4.2.10 on 2025-08-31 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributionevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contribution Event', 'verbose_name_plural': 'Contribution Events'},
        ),
        migrations.CreateModel(
            name='SchoolSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('junior_secondary', 'Junior Secondary'), ('senior_secondary', 'Senior Secondary')], max_length=50)),
                ('display_name', models.CharField(help_text="Custom display name (e.g., 'Primary School')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(blank=True, help_text='Override school currency if different', max_length=3)),
                ('timezone', models.CharField(blank=True, help_text='Override school timezone if different', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='contributions.school')),
                ('section_head', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'teacher']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Section',
                'verbose_name_plural': 'School Sections',
                'db_table': 'school_sections',
                'ordering': ['school', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contributionevent',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contribution_events', to='contributions.schoolsection'),
        ),
        migrations.AddField(
            model_name='group',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='contributions.schoolsection'),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='contributions.schoolsection'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'section')},
        ),
    ]
